### ISSUE TITLE
Updated Dashboard to display more than one sensor

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#1]
Right now that dashboard is hardcoded to only display data from a single sensor. This should be improved to display a world map with multiple senors and display the graphs for a selected sensor.

https://github.com/Ribbit-Network/ribbit-network-dashboard/blob/main/app.py contains the main application logic and all plots.

**Comment by yuzhang0302** [comment]
I can take this one!

**Comment by keenanjohnson** [comment]
Awesome! Thank you!

**Comment by keenanjohnson** [comment]
@brianstrauch this issue is high priority for us. @yuzhang0302 is already taking a look, but this could be a good intro to front end work in Dash (our web framework) if you're interested?

**Comment by yuzhang0302** [comment]
@brianstrauch do you have any idea of how we can make the first map_fig interactive with the line plots? I'd love to see ability to select a point on the map and the line plots would show or highlight data correlating to just that location. But not quite sure how to go about doing that

**Comment by keenanjohnson** [comment]
I think we might be able to handle an "Input('choropleth', 'clickData')" event like [in this example](Input('choropleth', 'clickData')) to get the clicked datapoint, which would allow us to change the display graphs below to that item.

**Comment by yuzhang0302** [comment]
@keenanjohnson can you relink the example? Not working

**Comment by keenanjohnson** [comment]
Oh whoops. Here's the link: https://towardsdatascience.com/highlighting-click-data-on-plotly-choropleth-map-377e721c5893

**Comment by keenanjohnson** [comment]
I did what I think the first step of this project is in [PR25](https://github.com/Ribbit-Network/ribbit-network-dashboard/pull/25). You can see I added a selector that allows the user to toggle which sensor is displayed in the graphs below. The two next steps would be:
1) Generate the sensor list from a query instead of a hard coded list
2) Allow this selection to be done by clicking on the map

https://github.com/Ribbit-Network/ribbit-network-dashboard/pull/25

**Comment by keenanjohnson** [comment]
I've gone ahead and merged that selector to main

**Comment by keenanjohnson** [comment]
@yuzhang0302 if you wanted to try and tackle generating the drop down list from a query, that would be awesome!

**Comment by brianstrauch** [comment]
If we plan on supporting 100+ sensors, I foresee a dropdown list getting out of hand... Also, how will a user know which sensor is "Sensor 1" or "Sensor 2"? My vote is to only allow selecting a sensor by clicking on it on the map.

**Comment by keenanjohnson** [comment]
Agreed! I just see the selector as an incremental step towards that :)

**Comment by keenanjohnson** [comment]
We've accomplished the original intent here to display data from multiple sensors. Just for clarity for people new to the project, I've created a new issue: #29 for the last remaining piece we've discussed here.
