### ISSUE TITLE
Identify Best Dashboard Hosting Service

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#100]
Currently, the website dashboard is hosted on the Heroku Free Tier of dynos. However, the free tier is being removed.

Since I am not aware of another free hosting service, we will need to start paying for hosting somewhere.

We should evaluate the best options and what would be the most cost-effective, while still easy to use hosting provider for the Ribbit Dashboard.

![image](https://user-images.githubusercontent.com/2559382/193337761-42549301-5dbc-4e5b-9250-543568f95e71.png)

**Comment by pascaljoly** [comment]
I've asked a friend who works for Platform.sh if they have discounts for
non-profits. they are a direct competitor with Heroku.

**Comment by pascaljoly** [comment]
also, have you looked at https://www.interserver.net/about/ ? they are free for non profit. I don't know how much flexibility they offer compared to a traditional PaaS.

**Comment by keenanjohnson** [comment]
I have not! @abhinavtripathy was going to compile a table of options this weekend I believe (or was that for the database hosting?) 

If so, we should consider it!

**Comment by abhinavtripathy** [comment]
Made an initial table of comparing supabase and firebase as options. Will add more. Others, please feel free to add more onto it. After 

Platform                                        | Database Type  | Database Storage | Database Reads/Writes                             | Hosting Limits                   | Auth                        | Serverless Support? | Serverless Functions Limits                             | Comments?                            |
| ----------------------------------------------- | -------------- | ---------------- | ------------------------------------------------- | -------------------------------- | --------------------------- | ------------------- | ------------------------------------------------------- | ------------------------------------- |
| [Firebase](https://firebase.google.com/pricing) | NoSQL          | 1 GB total       | 10 GB/month egress, 20k/day writes, 50k/day reads | 10GB storage, 360MB/day transfer | Yes, 50k/month active users | Yes                 | Only on pay as you go plan, 2 million invocations/month | There is decently high vendor lock in |
| [Supbase](https://supabase.com/pricing)         | SQL (postgres) | 500 MB total     | 2 GB/month egress                                 | No hosting available             | Yes, unlimited users        | Yes                 | 500k invocations per month                              | Decently high vendor lock in          |


@keenanjohnson I am actually quite interested in the free tier of AWS, they have fairly high limits for beginner projects. On top of that we can reach out here for a non-profit grant: [here](https://aws.amazon.com/government-education/nonprofits/?wwps-cards.sort-by=item.additionalFields.sortDate&wwps-cards.sort-order=desc).

**Comment by pascaljoly** [comment]
Do you have the optimal sizing specs of what we need? Is the database between NoSQL and SQL? what about the web server hosting for the dashboard? storage sizing?

**Comment by keenanjohnson** [comment]
The database we currently are using is InfluxDB, though that is up for debate pending the results of #81.

There is no storage for the web server at the moment on the free heroku tier.

**Comment by keenanjohnson** [comment]
Hey @pascaljoly ! it's a bit confusing, because InfluxDB is a database, but we use the hosted version of InfluxDB which is also a service called InfluxDB cloud. Our hosting isn't changing there, so I think discussing that is a bit out of scope for this issue and we should keep that conversation to #81. This is specifically just about the web server to host the front end page.

**Comment by keenanjohnson** [comment]
@abhinavtripathy thanks for starting that comparison! I wonder how AWS would compare to something like Digital Ocean which has a similiar grants program for non-profits: https://www.digitalocean.com/community/pages/hollies-hub-for-good

Would you be able to add AWS and Digital Ocean to your comparison table?

**Comment by abhinavtripathy** [comment]
@keenanjohnson sure! I will add digital ocean and AWS to the table. Give me a few days to go through the details.

**Comment by abhinavtripathy** [comment]
Also on a side note, I am a huge fan of digital ocean, they do some great work!

**Comment by pascaljoly** [comment]
Let's add platform.sh to the list. https://platform.sh/.
thanks!

**Comment by pascaljoly** [comment]
sorry about that I misunderstood. If it's just the web server then it's
much simpler.

**Comment by keenanjohnson** [comment]
Thanks @pascaljoly and @abhinavtripathy !

**Comment by keenanjohnson** [comment]
Thanks to our friends at platform.sh, they have offered us hosting on their platform for free as a non-profit, so we have migrated our site there.

I'm going to update the links on our main page and close out this issue.

**Comment by keenanjohnson** [comment]
platform.sh site is live at main-bvxea6i-lqkafs6clpkma.us-4.platformsh.site

**Comment by pascaljoly** [comment]
do we have a plan to update the DNS to have a ribbitnetwork alias? we can then update the links "Live Data" from the website

**Comment by keenanjohnson** [comment]
Yes I’m actually working that in discord right now :). I’ll update this
issue with links once I have everything configured properly :)
