### ISSUE TITLE
clean up menu on dashboard

### ISSUE THREAD

**Issue by pascaljoly** [Ribbit-Network/ribbit-network-dashboard#104]
the top menu of the dashboard has a **Learn** that redirects to the root website ribbitnetwork.org. Now that we have an **FAQ** we should remove it and instead make the **Ribbit Network** on the left side clickable to redirect to the root website.

**Comment by keenanjohnson** [comment]
Completed  in https://github.com/Ribbit-Network/ribbit-network-dashboard/pull/108
