### ISSUE TITLE
Set up Web Dashboard for Lab Validation Testing

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#105]
We have a Frog Sensor that has been sent to a test lab partner for validation of the sensing accuracy.

To support this testing we need branch of the frog software that does not require GPS and has a polling every 2 sec that can be downloaded from the dashboard website.

**Comment by keenanjohnson** [comment]
@pascaljoly I'll be starting work on this here.

**Comment by keenanjohnson** [comment]
To achieve this, I plan on doing the following:

* Creating a new InfluxDb Bucket (our database) to host this testing data so that it is not conflated with the other community Frog Sensors
* Creating a new validation Ribbit Network Balena fleet and moving the sensor currently at the test lab to that separate fleet
* Branch the ribbit network code to display only the single sensor at the testlab's data minus the map interface and with an increased sampling rate
* Deploying a test branch of the Frog Software to the new balena fleet that publishes to the validation database.

**Comment by keenanjohnson** [comment]
I created a new branch of the Frog software here: https://github.com/Ribbit-Network/ribbit-network-frog-sensor/tree/lab-testing/lab_testing/software

This branch now has a folder of software that publishes to the new influxDB bucket. I've switched the sensor at the lab to use this software.

<img width="2110" alt="image" src="https://user-images.githubusercontent.com/2559382/204123118-c56ac4b8-3065-4661-93b5-c1eaa23a0a1f.png">


Now all that is left is to remove the map on this branch of the dashboard and deploy it.

**Comment by keenanjohnson** [comment]
Ok @pascaljoly I believe this is now complete and ready for use! 

I created a new branch of the web dashboard software (source code)

[That site is now deployed here (sorry for the ugly URL)](https://105-set-up-web-for-lab-o7lrtxq-lqkafs6clpkma.us-4.platformsh.site/)

I've made it so that the site doesn't do any data averaging and has an option for the maximum sensor sample rate (2 seconds).

Anything else you think we should add here?

<img width="1796" alt="image" src="https://user-images.githubusercontent.com/2559382/204126776-43f2b0b3-270c-41c7-973d-52d848a65836.png">

**Comment by pascaljoly** [comment]
Thanks! does it require a specific update (reflash) on his sensor or is it done automatically?

**Comment by pascaljoly** [comment]
got it! I've notified Sebastien about it. once he starts using it we can close the issue?

**Comment by keenanjohnson** [comment]
Sounds good!

**Comment by spestana** [comment]
Have you thought about providing a script to download data at regular intervals they can run as a cron job or something like that?

I've been using [this ](https://gist.github.com/spestana/dfa9d0715b75201625dfe25b92756108) to archive data myself

**Comment by keenanjohnson** [comment]
Not sure. @pascaljoly do you think that would be useful?
