### ISSUE TITLE
Add data disclaimer

### ISSUE THREAD

**Issue by spestana** [Ribbit-Network/ribbit-network-dashboard#107]
Currently we're showing raw data direct from the network on the dashboard, and this raw data is downloadable there too.

I think we need a "disclaimer" stating that these data are raw, haven't been quality controlled, and haven't had any calibration/corrections applied (aside from whatever factory calibration the sensors received).

I'm thinking a short statement (and link to the FAQ) on the dashboard page itself (perhaps next to the download button below the map), and then also add more information about this to the FAQ.

**Comment by spestana** [comment]
Here's a draft of the text: https://docs.google.com/document/d/1AThfZEEU9wp7KP7n3t-sX6oHqOwDnfrWvliiJcLNEj4/edit?usp=sharing

**Comment by keenanjohnson** [comment]
I created a branch https://github.com/Ribbit-Network/ribbit-network-dashboard/tree/107-add-data-disclaimer here to make the change.

**Comment by keenanjohnson** [comment]
Were you planning on making the update @spestana or want me to push it to the site?

**Comment by spestana** [comment]
I'll open a PR to that branch. thanks!
