### ISSUE TITLE
Add Timezone indicators or localize data to the Browser Timezone

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#11]
Sensors should have time zones stamps on their respective data they capture based on their location of course. Such that the CO2 plots on the webpage will display data with the time zone stamps.

**Comment by yuzhang0302** [comment]
In addition: the sensor we currently display should be in PST, but the line plot doesn't seem to be. It's currently 8/30 9:45pm but displays 8/31 4:45am.

**Comment by keenanjohnson** [comment]
I think it's currently showing UTC time.

**Comment by Alhaji-trujillo** [comment]
More of the reasons why we need to indicate a timezone label on the plot in prep for integration of more sensor points
