### ISSUE TITLE
Make it clear what sensor is selected

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#123]
It's not obvious what sensor is selected on the map in the dashboard. We should make it more clear, either by highlighting the sensor that is selected or some other method.

<img width="1155" alt="image" src="https://github.com/Ribbit-Network/ribbit-network-dashboard/assets/2559382/bdb4a0e9-a6c1-4665-a5f0-1a1dd7c9703a">

**Comment by xxdavexx23** [comment]
Assign this to me. Would love a side project to work on!

**Comment by keenanjohnson** [comment]
Sure thing! Thanks @xxdavexx23 !

**Comment by keenanjohnson** [comment]
Let me know if you have any questions and check out the other open issues if you are looking for some additional projects here :)

**Comment by xxdavexx23** [comment]
just made a pull request please take a look when you get a chance.
