### ISSUE TITLE
Replace globe with 2D map

### ISSUE THREAD

**Issue by brianstrauch** [Ribbit-Network/ribbit-network-dashboard#14]
As the number of sensors grow, the current globe model will start to lag (since all points are shown at once). We should use the following and render only the visible sensors: https://plotly.com/python/scatter-plots-on-maps/

**Comment by spestana** [comment]
I tried my hand at replacing the globe with a different map style in #16 . It's also set up to color points based on the latest CO2 measurement.

**Comment by keenanjohnson** [comment]
I guess I don't really understand why this flat map would perform better than the globe?

**Comment by spestana** [comment]
Right, I'm not sure if the globe actually loads more slowly than other types of plots?

**Comment by brianstrauch** [comment]
The idea is that as we get more and more sensors, we'll have to query data for all of them, and render all of them. For 100+ sensors this could take a lot of time.

If we use a 2D graph, we only need to query the sensors within the box that's currently visible on the screen. InfluxDB can do this really efficiently.

**Comment by keenanjohnson** [comment]
So are you imagining that eventually we'll have some logic that wouldn't show the whole map when the page loads initially? I guess if that's the case this makes sense. I'm a bit sad because I thought the globe looked nice, but understood if you all feel the flat map is the way to go.

**Comment by brianstrauch** [comment]
Yeah, that's what PurpleAir does. Looks like they have well over 1000 sensors. Try zooming out all the way and watch how long it takes for everything to load (https://www.purpleair.com/map?opt=1/mAQI/a10/cC0#0.25/0/-122.1)

**Comment by keenanjohnson** [comment]
Makes sense to me :)

**Comment by brianstrauch** [comment]
Some other ideas though (because the globe is pretty cool):
1. When we hit 100+ sensors only show a subset of them on the globe
2. Lazily load all of the sensors, i.e. query 100 sensors at a time until all of them are shown

**Comment by keenanjohnson** [comment]
I merged the PR to move to the flat map for now. We can always go back if we like this look less :).

Thanks all!

![image](https://user-images.githubusercontent.com/2559382/132250863-38264933-7985-4577-8599-251b7711c24b.png)
