### ISSUE TITLE
Data granularity and precision

### ISSUE THREAD

**Issue by yuzhang0302** [Ribbit-Network/ribbit-network-dashboard#19]
We are currently pulling data every few seconds, I think we should establish a less granular approach (maybe every minute, 5 minute or 15 minute, not sure).
Also when we are hovering over the map or graph, it displays 6+ decimal places for CO2 reading, I think this is a bit too precise, data should be displayed to 2 decimal points?

**Comment by brianstrauch** [comment]
From what I can tell, the `interval-component` is causing data to be queried every 60 seconds: https://github.com/Ribbit-Network/ribbit-network-dashboard/blob/af3eb2b9928c587de7255f9bff930b9cc949233c/app.py#L52. My vote is actually to increase this to every second, so we can display a real-time map and graph.

Agree with your point about the CO2 readings though.

**Comment by yuzhang0302** [comment]
The interval component you pointed to is actually the frequency that the web-browser refreshes the data. Currently the data is recorded once every 2 seconds and that's how low it goes. 

I think ultimately the use case for this type of data would be a minute or more. Anything more granular wouldn't be super helpful. We can also make this a parameter defined by the user similar to what you've doing with the duration of data?

**Comment by brianstrauch** [comment]
@yuzhang0302 Oh, I see. In that case, my intuition is that minute-long intervals would work well; we should move that discussion to the https://github.com/Ribbit-Network/ribbit-network-frog-sensor repo though.

**Comment by spestana** [comment]
As for the precision that's reported, the accuracy is listed as +/- 30 ppm + 3% for CO2 (also accuracy changes with temperature), +/- 3% for relative humidity, and about +/- 4 C for temperature (also temperature dependent). ([see the SDC30 datasheet](https://cdn-learn.adafruit.com/assets/assets/000/098/461/original/Sensirion_CO2_Sensors_SCD30_Datasheet.pdf?1609871944))

Reporting CO2 to the nearest 1 ppm might be ok but would show more noise than rounding to like 10s of ppm. And I think similarly with temperature rounding to the nearest whole degree (C or F), and RH to the nearest 1% would show a little noise but be alright.

**Comment by spestana** [comment]
Any thoughts on obfuscating the precise GPS locations (as sort of a privacy/security consideration)?

I would think this can be done on the raspberry pi before sending the data upstream?

**Comment by brianstrauch** [comment]
Definitely a good idea! For complete privacy it should be done on the pi. Possible approach:

1. If privacy is desired, the user generates a random number and stores it locally on the pi (in a config file).
2. A deterministic function maps it to an angle between 0 and 360.
3. All GPS coordinates are translated to a point a few blocks away (maybe 1/4 of a mile) in the direction of the angle.

**Comment by keenanjohnson** [comment]
Obfuscation of the location is definitely an important topic that we should
come to a stance on. I’ve gone back and forth on this a few times and
curious what you all think. The value to scientist and policy makers is
significantly reduced if the location accuracy is diminished. Additionally
the sensors don’t log or have access to any user information. Given those
two facts, I’ve up this point opted to keep the location data accurate.

My only comparison for this is PurpleAir, which publishes highly accurate
location data and people seem generally accepting, but curious to know if
that makes sense to you all?

**Comment by brianstrauch** [comment]
These sensors seem pretty expensive, so it seems possible that they could potentially be stolen for their parts (from the perspective of an adversary, this website is a map of free raspberry pis).

We could let users optionally obfuscate their location and add a boolean field `isObfuscated` to the data set that researchers could filter against if their research can't tolerate GPS data that's off by a few yards.

Another option is just to add a note to the FAQ suggesting that people install them in a secure location (i.e. behind a gated fence). From the PurpleAir FAQ:
> This is a personal preference but we suggest to install it closest to the street but behind 
a gate/fence to avoid the sensor being stolen.

**Comment by keenanjohnson** [comment]
That is definitely a concern if that is a scenario that starts to occur. Given that our sensors are cheaper than PurpleAir sensors and the installation note seems to be enough for them, I would prefer to stick with adding an installation guide note about the location for now and only add the obfuscation feature if we see start to see incidents of stolen sensors.

**Comment by spestana** [comment]
> The value to scientist and policy makers is significantly reduced if the location accuracy is diminished. 

Unless someone is doing very [fine spatial scale research (such as by city block, which would require a very dense network of frog sensors)](https://www.ce.washington.edu/news/article/2021-06-15/clearing-air) I would guess that accuracy within +/- 100 meters is plenty good.

**Comment by keenanjohnson** [comment]
@yuzhang0302  did an awesome job addressing the data precision for the UI display in the commits above. The discussion here about GPS obfuscation is important, so let's move that to a discussion: https://github.com/Ribbit-Network/ribbit-network-dashboard/discussions/27
