### ISSUE TITLE
Select Sensor Via Map Location Click

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#29]
Currently, the graphs display a sensor's data based on which sensor is selected in a drop-down menu. 

As discussed in #1 we should update this to Allow this selection to be done by clicking on a sensor in the map.

This seems technically feasible according to this tutorial: https://towardsdatascience.com/highlighting-click-data-on-plotly-choropleth-map-377e721c5893

**Comment by Alhaji-trujillo** [comment]
You can assign this to me @keenanjohnson

**Comment by Alhaji-trujillo** [comment]
Thanks

**Comment by keenanjohnson** [comment]
Done!

**Comment by keenanjohnson** [comment]
@brianstrauch you've been doing such awesome work on this project! If you're looking for something else to tackle, I think this one could be a real usability improvement for the site! I thought I had it, but I had clearly introduced a bug previously so I rolled back the change.
