### ISSUE TITLE
Figure out if the InfluxDB Database Structure is optimal for GeoLocated CO2 Measurments

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#3]
Currently the ribbit network sensors publish each measurement to the InfluxDB Database like this:

```
# Publish to Influx DB Cloud
point = Point("ghg_point").tag("host", device_uuid) \
        .field("co2", scd.CO2).time(datetime.utcnow(), WritePrecision.NS) \
        .field("temperature", scd.temperature) \
        .field("humidity", scd.relative_humidity) \
        .field("lat", latitude) \
        .field("lon", longitude) \
        .field("alt", altitude)
```

See the sensor source file here for more information: https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/main/software/co2/co2.py

I could use some help from an InfluxDB expert to figure out if this is the optimal schema for location-based data. Specifically, what's the right way to optimize this for queries later in the dashboard or for the science datasets?

**Comment by keenanjohnson** [comment]
@brianstrauch this issue might be a good short-term item you could help with?

**Comment by brianstrauch** [comment]
The current schema looks good, although it depends what our long-term goals are.

A no-brainer is we'll want a dashboard that queries the "frogs" currently on the screen (inside a rectangle). InfluxDB does this for us: https://docs.influxdata.com/influxdb/cloud/query-data/flux/geo/filter-by-region/#box

We might also want to query all of the "frogs" in a given country, in which case we might be able to input polygons for different countries (from here for example: https://github.com/datasets/geo-countries) into this filter: https://docs.influxdata.com/influxdb/cloud/query-data/flux/geo/filter-by-region/#polygon

Are there any other use cases I'm missing?

**Comment by brianstrauch** [comment]
It looks like the InfluxDB Geo package also requires an `s2_cell_id`: https://docs.influxdata.com/influxdb/cloud/query-data/flux/geo/shape-geo-data/

I think right now it makes sense to generate these as part of the query, but in the future, a good performance improvement would be to generate several (or maybe all 15) different IDs (one for each `level`) when a data point is written to the DB.

**Comment by keenanjohnson** [comment]
Yeah I think that is all the usecases so far @brianstrauch! I'm going to close out this issue since it seems like the structure is adequate for now! Yeah the cell generation is certainly an interesting idea! We could easily generate those on the sensor before writing up to the database.
