### ISSUE TITLE
Switch to subplots for line graph

### ISSUE THREAD

**Issue by yuzhang0302** [Ribbit-Network/ribbit-network-dashboard#30]
Instead of generating 4 different graphs, we should use subplot

**Comment by sriki18** [comment]
Hello, I can look into this @keenanjohnson . Anything I should keep in mind before I get started?

**Comment by sriki18** [comment]
Okay, I have started work on this! I will keep the loading animations and mobile in mind. Not sure how you test mobile, but I plan on using the mobile mode in Firefox - let me know if there is a more sophisticated tool!

Do you have thoughts on Plotly express vs using the low level functions(e.g. `go.line`) ? It looks like using Plotly express doesn't play too well with subplots (https://github.com/plotly/plotly_express/issues/83). I created a mock-up using a "long" dataframe

```{python}
df1 = pd.DataFrame({"Time":[1,2,3,1,2,3], "y":["CO₂ (PPM)", "CO₂ (PPM)", "CO₂ (PPM)", 'Temperature (°C)', 'Temperature (°C)', 'Temperature (°C)'],
    "Value":[1,2,3,4,5,6]})
```

![image](https://user-images.githubusercontent.com/7760814/136481261-ff343cac-3730-4cd2-86d1-babfc9fc25c2.png)

We can resolve the CO2 (PPM) and Temperature (C) appearing on the right by using Plotly low level functions at the cost of having more bloated code. Let me know what you think @keenanjohnson !

**Comment by keenanjohnson** [comment]
Yeah I think testing via the mobile browser should be fine :)

I'm definitely not an expert on Plotly express vs the low-level functions, so happy to take a look at whichever direction you feel is best.

**Comment by keenanjohnson** [comment]
@allcontributors please add @sriki18 for his great code contributions!

Thanks @spestana for the review!
