### ISSUE TITLE
Create user input for report frequency

### ISSUE THREAD

**Issue by yuzhang0302** [Ribbit-Network/ribbit-network-dashboard#31]
Create a dropdown for user to specify reporting frequency, default to 1 minute, options for 5 min, 15 min, 30 min, 1 hour

**Comment by spestana** [comment]
Check out my attempt at adding a sampling frequency option to the dashboard  (#85 ) and let me know what you think!

**Comment by keenanjohnson** [comment]
Yeah will do!
