### ISSUE TITLE
Display a Loading Icon or Text While Graphs are Updating

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#32]
The queries can sometimes take a second or two depending on the length of data queried. Although the page title shows "Updating" while this is happening, it would be nice to add something more obvious to show that the page is loading on the graphs themselves.

**Comment by keenanjohnson** [comment]
It looks like this can be accomplished via the Loading states in Dash: https://dash.plotly.com/loading-states

**Comment by rishikavikondala** [comment]
@keenanjohnson - which of these options do we want?
Option 1: have a single loading icon above the first graph to indicate that all graphs are loading 
Option 2: have a separate loading icon for each graph

**Comment by keenanjohnson** [comment]
@rishikavikondala I think either is fine!
