### ISSUE TITLE
Display Sensor Aggregate Numbers if Multiple Sensors Are in One Location

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#39]
Given that the sensors obfuscate their GPS location, it's possible to have multiple sensors display in the same location on the map. If this happens, we should display a number of sensors on top of that dot to indicate the number of sensors deployed there.

**Comment by brianstrauch** [comment]
I think we should generalize this to any zoom level. For instance, when the map is zoomed all the way out, it looks like there's only one sensor in Seattle. We should combine sensors whenever they're **visually** on top of each other, not just at the same coordinates.

**Comment by keenanjohnson** [comment]
Yes that's a great suggestion!

**Comment by sagunn** [comment]
I cannot find support for point clustering like this in Plotly's scattermapbox.
Discussion here: https://community.plotly.com/t/how-to-use-mapbox-clusters/10774

Looks like maybe using dash-leaflet to render the map could do the trick. 
See http://dash-leaflet.herokuapp.com/#marker_cluster

**Comment by keenanjohnson** [comment]
Thanks for looking into that @sagunn ! Perhaps we should trick switching to that map rendering! It looks promising and to be honest, it seems like they are using the same mapbox tiles anyway haha
