### ISSUE TITLE
Developer Discord link is invalid

### ISSUE THREAD

**Issue by bcran** [Ribbit-Network/ribbit-network-dashboard#4]
The developer discord link at https://github.com/Ribbit-Network/ribbit-network-dashboard is invalid. When I click it, I get the message:

Invite Invalid
This invite may be expired, or you might not have permission to join

**Comment by keenanjohnson** [comment]
Oh noooooooo let me fix that now

This link should work I believe: https://discord.gg/vq8PkDb2TC

**Comment by keenanjohnson** [comment]
Link updated! Let me know if that worked!

**Comment by bcran** [comment]
That works now - thanks!
