### ISSUE TITLE
Add basic unit tests

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#40]
Right now the project has no unit tests. We should add some basic tests :)

**Comment by sriki18** [comment]
Hmm. We could probably split this into two problems, one for db tests and one for the dash app. The former should not be too hard - hard-code some queries and check data consistency. Dash app tests may be a little more involved (https://dash.plotly.com/testing). Am I missing anything?

**Comment by keenanjohnson** [comment]
Yeah I think those are the two major pieces right now. Probably something like a basic smoke test just to ensure the dash app runs for example would be key.

There are other things we could eventually test like that the plots auto update and the clicking behaviors work correctly, but those are of lesser value right now I think.

**Comment by keenanjohnson** [comment]
@all-contributors please add @abesto for his awesome test code!

**Comment by keenanjohnson** [comment]
I've added the ability to trigger the actions manually above and [it works great](https://github.com/Ribbit-Network/ribbit-network-dashboard/actions/runs/1652149353):

![image](https://user-images.githubusercontent.com/2559382/148010564-a3ba43b1-537c-42f6-a3bc-87febb759f7a.png)

**Comment by keenanjohnson** [comment]
Per our discussion in #67 @abesto, I've created #70.
