### ISSUE TITLE
Web Page is Hard to Use on Mobile

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#45]
@spestana pointed out that the web site is really quite hard to use on mobile. When you try to scroll up and down on the page, you instead select areas on the plots frustrating haha. See my screen recording below.

https://user-images.githubusercontent.com/2559382/134118492-0c947438-f8ed-4d7c-adc5-40090d9024ec.MP4

I'm not sure what the best solution here is quite yet. Mobile isn't really a usecase I had originally designed for, but it seems quite important. Perhaps some better web framework would help solve this or perhaps there are some easy settings in the plot interactions that we could tweak to make this better.

**Comment by brianstrauch** [comment]
To accomplish #39, we're planning to switch to dash leaflet. We can use this to require two fingers to scroll the map: https://dash-leaflet.herokuapp.com/#gesture

**Comment by keenanjohnson** [comment]
That would definitely help, but I think the main issue is with the plots below, not the map :)

**Comment by spestana** [comment]
I am going to close this issue. Changing the graph widths fixed the main problem of not being able to scroll down the page.
There are probably other improvements that could be made for small touchscreen devices, but those could be separate issues if they become a priority.
