### ISSUE TITLE
Improve the Visual Design

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#5]
The visual design of the sight is.... quite bland to say the least. Let's make it look good, hopeful, inspiring, and useful.

![image](https://user-images.githubusercontent.com/2559382/131021482-6f3ea917-a6cd-4ba5-b6a3-e6c3af4c4e5d.png)

**Comment by Alhaji-trujillo** [comment]
You can assign this to me

**Comment by keenanjohnson** [comment]
@Alhaji-trujillo needs to step away for a bit to focus on other work. Unassigning for now.
