### ISSUE TITLE
Fix Map Infinite Panning

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#60]
From Frog User: "they panned the wrong way on the map and couldn't find our dot as it only appears once while the map loops infinitely."

I'm not sure if the right way to fix this is to fix the infinite panning or replicate the point on the amp, but we should fix it.

**Comment by keenanjohnson** [comment]
Thanks for tackling this change so quickly @spestana! This looks pretty good except, I think it might be good to move the limits out a bit wider than 180 degrees so that if there is a sensor in the extreme margin, someone can scroll such that their sensor in New Zealand for example, is in a useable section of the map.

**Comment by brianstrauch** [comment]
Was this issue closed by #61?

**Comment by spestana** [comment]
> Was this issue closed by #61?

Yes, I'll close this now!
