### ISSUE TITLE
Prevent Lat:0, Long:0 GPS coordinates from Appearing on Map

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#62]
@spestana noticed that someone was publishing a 0,0 GPS coordinate on the map, likely due to someone's software erroring for some reason.

We should screen these out somehow. Perhaps by showing a second page of senors that have default locations for example.

![image](https://user-images.githubusercontent.com/2559382/142940856-1bbbe366-721a-4faa-be68-96fb7da47540.png)

**Comment by sriki18** [comment]
Can we simply add a filter near here? 

https://github.com/Ribbit-Network/ribbit-network-dashboard/blob/8f04d07e97056d535bfbcabeed98f02800061dc6/db.py#L9-L14

Just filtering out lat=0 & lon=0 over when querying the map.
