### ISSUE TITLE
Add Additional Data to each Sensor

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#7]
Currently, the webpage only displays CO2 PPM, however, we are logging several other data items that we should display.

See here for the list of other items logged:

https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/c68b315058ff87d62d956845ab954f054d8c7f9e/software/co2/co2.py#L106-L116

**Comment by yuzhang0302** [comment]
I plan on tackling this :)
