### ISSUE TITLE
Explanation Infographics

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#74]
We should ceate a series of infographics explaining how the Ribbit Network generates a heatmap of CO2 data from a network of sensors to tell the story of how Ribbit Network works and why that matters.

This can help us answer questions like:

* Why do we need so many sensors?
* How do we determine where emissions come from using the sensors?

**Comment by nivashini10** [comment]
I worked on Canva and created a draft of the infographics. This allowed me to learn the tools and features in canva and brainstorm some ideas for the final infographic. 

I have attached the infographic here and the [link ](https://www.canva.com/design/DAE8xzxhd9w/yYBcEJB2iK4RWU_5WtnzQg/watch?utm_content=DAE8xzxhd9w&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel)for it.

![Ribbit Network Infographic](https://user-images.githubusercontent.com/70036680/161406506-22147a1d-c904-40b1-9a44-0e5c8b87c9bc.gif)

Would love any feedback on it!

**Comment by nivashini10** [comment]
My inspiration for the infographic is https://www.saveonenergy.com/how-wind-turbines-work/. I really liked how it is structured and interactive, and want to build the infographic incorporating some of its elements.

**Comment by keenanjohnson** [comment]
OMG THIS IS THE BEST @nivashini10 !!!! This is exactly what I hoped, but even better!

The biggest piece of feedback I have is that perhaps it could use one final section with something about our hopes for how the data is used. Something like:

**Impact**
Ribbit Network is a non-profit, 501(c)(3), that is committed to keeping this dataset free and available to all. This will allow citizen scientists, corporations, and governments to take informed action and hold each other accountable.

**Comment by Derek-Gutheil** [comment]
This is beautiful!

**Comment by keenanjohnson** [comment]
I think this is really solid and closing this issue for now.
