### ISSUE TITLE
Show Sensors That were Previously "Online" on Map

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#86]
One improvement I have been thinking about is maybe a good task for anyone looking to help do more web development on! Right now the web dashboard only shows sensors that return data that have sent data within the latest query time. However, there are lots more sensors that come on and offline that contributes valuable data. We could improve the site such that it displays all sensors that have previously been online!

**Comment by abesto** [comment]
I'm starting to look into this!
