### ISSUE TITLE
time scale display on all graphs / heroku

### ISSUE THREAD

**Issue by pascaljoly** [Ribbit-Network/ribbit-network-dashboard#98]
when I look at the graphs on https://ribbit-network.herokuapp.com/ the time scale is only displayed in the last graph (Humidity). Can we also add it to the other graphs?
CO2 concentration, temperature, pressure...

**Comment by keenanjohnson** [comment]
Hey @jklmaynard ! Thanks for jumping in here! Your local server should have access to the data. 

You followed the run instructions in the readme here correct?

https://github.com/Ribbit-Network/ribbit-network-dashboard#technical-details

**Comment by jklmaynard** [comment]
@keenanjohnson yessir, that part was straightforward.  I'll run the requirements install again, just to see if something broke. The error on my local server looks like this:

<img width="575" alt="Screen Shot 2022-09-28 at 5 55 59 PM" src="https://user-images.githubusercontent.com/9573898/193051919-e972bf1c-5543-4402-89de-c6acbe26f0b5.png">

The variables in the influx_config file are all up to date, I assume?

**Comment by keenanjohnson** [comment]
Hmm interesting. Those variables should be correct as this repo gets literally auto-deployed from github via Heroku.

Are you on a macbook perchance? I know that sometimes there can be issues with local certificates.

Perhaps you could try this? https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

<img width="741" alt="image" src="https://user-images.githubusercontent.com/2559382/193122297-307f7751-7218-47e0-bd9c-6c7575eb9404.png">

**Comment by jklmaynard** [comment]
@keenanjohnson nice, that did it!  I can add that to the readme if you'd like.

**Comment by keenanjohnson** [comment]
Glad that was an easy fix @jklmaynard ! Yes that would be quite helpful! Are you familiar with forking / creating a PR?

**Comment by jklmaynard** [comment]
Yep, seems pretty clear from the guidelines.  I had just cloned directly from here, but I'll go and fork it first then send it up.  I should have a PR for this tonight (Pacific Standard) unless somebody is able to make the change first.  My recommendation seems to have solved it:

Here's for 7 days:
<img width="762" alt="Screen Shot 2022-09-29 at 3 39 25 PM" src="https://user-images.githubusercontent.com/9573898/193154485-17366393-9249-479f-89ab-97c2978960d3.png">
 Here's for 1 day:
<img width="725" alt="Screen Shot 2022-09-29 at 3 39 33 PM" src="https://user-images.githubusercontent.com/9573898/193154500-8421c1aa-855d-4390-b2e4-8dc056040a5b.png">

**Comment by keenanjohnson** [comment]
Thanks so much @jklmaynard ! Let me know if you run into any issues!

**Comment by keenanjohnson** [comment]
Thanks!
